# Generated by Django 4.1 on 2022-08-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=200)),
                ('Website_URL', models.CharField(max_length=10000)),
                ('Phone', models.CharField(max_length=50)),
                ('contact', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('Job_responsibilities', models.TextField()),
                ('subject', models.TextField()),
                ('Requirements', models.TextField()),
                ('Experience', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=10000)),
                ('City', models.CharField(max_length=10000)),
                ('State', models.CharField(max_length=10000)),
                ('Education', models.CharField(max_length=10000)),
                ('Experience', models.TextField(max_length=12122)),
                ('LinkedIn', models.CharField(max_length=12122)),
                ('GitHub', models.CharField(max_length=12122)),
                ('About', models.TextField()),
                ('Skills', models.TextField()),
                ('file', models.FileField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=130)),
                ('TimeStamp', models.DateTimeField(blank=True)),
                ('image', models.ImageField(default='', upload_to='home/images')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='home/images')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('desc', models.CharField(default='', max_length=25015)),
                ('athour', models.CharField(max_length=1023)),
                ('slug', models.CharField(max_length=130)),
                ('TimeStamp', models.DateTimeField(null=True)),
            ],
        ),
    ]
