# Generated by Django 4.1 on 2022-09-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prize',
            field=models.CharField(choices=[('0-500$', '0-500$'), ('500-1000$', '500-1000$'), ('1000-5000$', '1000-5000$'), ('5000 - 10000$', '5000 - 10000$'), ('10000$', '10000$')], default='', max_length=10010),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.CharField(choices=[('UI / UX Design', 'UI / UX Design'), ('Web Design', 'Web Design'), ('Wordpress Web Design', 'Wordpress Web Design'), ('Graphic Design', 'Graphic Design'), ('3D Animition Design', '3D Animition Design'), ('Digital Marketing', 'Digital Marketing'), ('Web Application Development', 'Web Application Development'), ('Flutter Application Development', 'Flutter Application Development'), ('Softwere Development', 'Softwere Development'), ('Data Analyst', 'Data Analyst'), ('Machine Learning', 'Machine Learning'), ('Artificial Intelligence', 'Artificial Intelligence')], default='', max_length=10010),
        ),
    ]
