# Generated by Django 4.1 on 2022-09-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_order_prize_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='certifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='home/images')),
            ],
        ),
    ]
