# Generated by Django 4.1 on 2022-10-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prize',
            field=models.CharField(choices=[('0-500$', '0-500$'), ('500-1000$', '500-1000$'), ('1000-5000$', '1000-5000$'), ('5000-10000$', '5000-10000$'), ('10000$', '10000$')], default='', max_length=10010),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(choices=[('Graphic Design', 'Graphic Design'), ('UI/UX Design', 'UI/UX Design'), ('3D Animition Design', '3D Animition Design'), ('Wordpress Design and Development', 'Wordpress Design and Development'), ('Web Design and Application Development', 'Web Design and Application Development'), ('Mobile Application Development', 'Mobile Application Development'), ('Softwere Development', 'Softwere Development'), ('Machine Learning', 'Machine Learning'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Data Analytics', 'Data Analytics'), ('Digital Marketing', 'Digital Marketing')], default='', max_length=10010),
        ),
    ]
